use_frameworks!
inhibit_all_warnings!

target 'MAGMessageService_Example' do
  pod 'MAGMessageService', :path => '../'

  target 'MAGMessageService_Tests' do
    inherit! :search_paths

    
  end
end
